### ISSUE TITLE
Add `updatedAt` and `createdAt` to `Index`

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-rust#187]
When manipulating indexes (get/create/update), the MeiliSearch server returns the following information related to the index:
- `uid`: the uid of the index
- `primaryKey`: the primary key of the index
- `updateAt`: when the index has been updated
- `createdAt`: when the index has been created

This SDK, when manipulating indexes (get/create/update) returns an instance of `Index` which already contains the `primaryKey` and `uid` members.

It means we can currently get the `primaryKey` and the `uid`, but not `updatedAt` and `createdAt`.

TODO:
- [ ] Add `updatedAt` and `createdAt` member in the `Index` class/struct (depending on the language).
- [ ] Update the variable in the code where `primaryKey` is already updated. Ex: when getting the index with `getIndex()`
- [ ] Add tests

⚠️ This issue is generated, it means `primaryKey`, `updatedAt`, and `createdAt` might be named differently in this package (ex: `primary_key` instead). Keep the already existing way of naming in this package to stay idiomatic with the language and the repository.
Also, if you are a maintainer, feel free to add any clarification and instruction about this issue related to the specific languages of the repo.

Related to https://github.com/meilisearch/integration-guides/issues/121

Sorry if this is already partially/completely implemented, feel free to let me know about the state of this issue in the repo.

**Comment by irevoire** [comment]
To implement that you should create two new `Option` fields in the `Index` to represents the `created_at` and `updated_at` field of the Json.
Once this is done you can update the `fetch_info` methods so instead of returning a `JsonIndex` it update the field inside of the `Index`.

Currently, in the rust-sdk there is no `primary_key` either, so if you decide to implements this issue it would be great to also add that as an optional field 👍

**Comment by abhizer** [comment]
Hi! I'm looking to contribute and had a question!  
@irevoire  Is the suggestion to change the return type of `fetch_info()` from `Result<JsonIndex, Error>` to `Result<(), Error>` and just update `self`? So, something like this: 
```rust
    pub async fn fetch_info(&mut self) -> Result<(), Error> {
        let v = request::<(), JsonIndex>(
            &format!("{}/indexes/{}", self.client.host, self.uid),
            &self.client.api_key,
            Method::Get,
            200,
        )
        .await?;
        self.primary_key = v.primaryKey;
        self.updated_at = Some(v.updatedAt);
        self.created_at = Some(v.createdAt);
        Ok(())
    }
``` 
I was thinking if `fetch_info` could update `self` and return `JsonIndex` as well? 
Because: 
Changing the return type of `fetch_info` would mean that methods that depend on it (`Client::get_raw_index` and such) would also need to be modified. As `get_raw_index` is supposed to return `JsonIndex` but `fetch_info` didn't, converting `Index` to `JsonIndex` inside `get_raw_index` would probably be a little redundant (as we converted it the other way around in `fetch_info`) and I tried implementing `TryFrom<Index>` for `JsonIndex` but as fields `created_at` and `updated_at` are optional, I was uncertain about unwrapping and am unsure as to what would be the ideal `Error` variant of `meilisearch_sdk::Error` to return. Another option would be to add `Index::into_json` which would be a private method only used within `get_raw_index` where we can unwrap safely.  

Looking forward to suggestions!

***
Note that the `Index` struct and `JsonIndex::into_index` method would be modified as follows: 
```rust
impl JsonIndex {
    pub(crate) fn into_index(self, client: &Client) -> Index {
        Index {
            uid: Rc::new(self.uid),
            client: client.clone(),
            primary_key: self.primaryKey,
            created_at: Some(self.createdAt),
            updated_at: Some(self.updatedAt),
        }
    }
}

#[derive(Debug, Clone)]
pub struct Index {
    pub(crate) uid: Rc<String>,
    pub(crate) primary_key: Option<String>,
    pub(crate) client: Client,
    pub(crate) updated_at: Option<OffsetDateTime>,
    pub(crate) created_at: Option<OffsetDateTime>,
}
```

**Comment by irevoire** [comment]
Hey @abhizer, sorry for the delay!

There are a lot of things with this issue. *PERSONALLY* and I may be wrong, this is how I see the thing;

First;
> @irevoire Is the suggestion to change the return type of fetch_info() from Result<JsonIndex, Error> to Result<(), Error> and just update self?
Yes, you're right.

Second, we should get rid entirely of the `JsonIndex` structure.
When you ask for a « raw » index in all the other SDKs, what you get is *the* JSON. Thus we should return a `serde_json::Value`. Maybe we could return a `serde_json::Map<String, serde_json::Value>` since we **know** it'll be an object. But I think that's unnecessary and we should directly return the `Value`.
And that means everywhere in the code of the SDK, when we were asking for a `JsonIndex`, we should stop and asks directly for an `Index`.

And I think that answers all the other questions, but it means we'll need to update a lot of code :unamused: 

-----------

Tell me if I was not clear.
Also, I would love to hear your opinion on the subject. And if some of you have the time, I would also love to get the opinion of @sanders41, @curquiza, @bidoubiwa or @brunoocasali if any of you have the time because I'm really not sure of what I'm proposing since it's my first SDK :joy:

**Comment by sanders41** [comment]
@irevoire I just have a quick minute and will come back and look at this closer when I have more time. For now [this discussion](https://github.com/meilisearch/meilisearch-python/issues/258) we had on the Python client may provide some insight here.

**Comment by abhizer** [comment]
@irevoire I think returning `Value` from `get_raw_index` makes sense from one point of view, but from another, doesn't the name `get_raw_index` feel a little misleading? Cause we're converting `Index` to `Value` and there's no "raw" element to it, ie, we aren't directly returning the piece of JSON returned by meilisearch (although the "raw" JSON returned by meilisearch is *probably* the same as the one we get by converting `Index` - that we deserialized from the JSON value we got - to `Value`). If the method `get_raw_index` was refactored to say, `get_json_index`, it'd make the purpose of the method a lot clearer. 

Say, meilisearch was updated to a newer version and returns more information that it currently does, we will miss out on it, and data will be lost between meilisearch and the user, as mentioned in: https://github.com/meilisearch/meilisearch-python/issues/258#issuecomment-835812331

Could we perhaps make a new method `fetch_info_raw` (name tentative), that returns the entire `String` returned by meilisearch, without us deserializing it ( as we aren't even deserializing it, it goes without saying that we aren't even updating `Index`)? And perhaps, `get_raw_index` could return the information returned by `fetch_info_raw`.

**Comment by irevoire** [comment]
Ah but yes, but to me, the `get_raw_index` should return the `Value` directly without deserializing it in any way for the reasons you stated.

Something like that;
```rust
    pub async fn get_raw_index(&self) -> Result<Value, Error> {
        Ok(request::<(), Value>(
            &format!("{}/indexes/{}", self.client.host, self.uid),
            &self.client.api_key,
            Method::Get,
            200,
        )
        .await?)
    }

    pub async fn fetch_info(&mut self) -> Result<(), Error> {
        let value = self.get_raw_index();

        self.updated_at = Some(value["updated_at"].ok_or(CreateAnError)?);
        ...
    }
```

Would that look correct to you?

**Comment by abhizer** [comment]
Oh yes, that makes a lot of sense actually!

So, the todolist for this change would be: 

- [ ] Add fields `updated_at`, `created_at` and `primary_key` to `Index`
- [ ] Make `get_raw_index` return the raw `Value` that's returned by Meilisearch
- [ ] Update `fetch_info` to update `Index` instead of returning `JsonIndex` 
- [ ] Remove `JsonIndex` and update everything (like `get_raw_index`) that relies on it to use `Index` 
- [ ] Tests

If this is correct, and I'm not missing anything significant, I'll get started and submit a PR

**Comment by irevoire** [comment]
Yep I think you're right :rocket: 
Thanks a lot you're the best :grin:

**Comment by sanders41** [comment]
Just getting a chance to come back to this. Nothing really to add other than to say this plan sounds like a good one to me.
