### ISSUE TITLE
Extend Document trait with function to get index

### ISSUE THREAD

**Issue by amaihoefner** [meilisearch/meilisearch-rust#444]
**Description**
Add a `index()` function to the `Document` trait to make it easier to get access to the index.

**Basic example**
Right now, something that implments `Into<String>` needs to be provided when one wants to get access to an index:
```rs
let movie_index = client.index("movies");
```

With this change one could instead write:
```rs
let movie_index = Movie::index(&client);
```
(Provided `Movie` implements the `Document` trait)
This way accessing an index becomes less prone to typos and one would'nt have to keep track of the name of the index, only the associated struct.

**Other**
It might also make sense to add a constant `INDEX_STR` to the trait.
This would have the following benefits:
- it could be used to provide a default implementation for the proposed `Document::index` function
- it could be used when implementing `Document::generate_index` by hand

Adding this to the derive macro would also not require much effort, as the index name is already being extracted there.

I will provide a draft merge request with these changes to act as a base for further discussion.

**Comment by bidoubiwa** [comment]
Hey @amaihoefner
thanks for raising this issue.

> But a Document type should not be tied to an index.

It is already the case, currently, the index_name is generated by snake_casing the Document structure's name. For example the Movie structure will have `movie` as an index_name. 

This confusion is due to the trait being very badly named. It helps generate the settings based on the schema of the document. Thus it's more an Index configuration/schema than a Document.

My suggestion would be: 
Rename the `Document` trait to `IndexConfig` or something better (if it's ok for you to do that in your PR).

In your PR, change 
```rust
    fn index(client: &crate::client::Client) -> Index {
``` 

to 
```rust
fn index(client: &Client) -> Index {
```
